---
#- name: Copy td.repo
#  template: src=beaker.repo dest=/etc/yum.repos.d/beaker.repo mode=0644
#
#- file: path=/etc/beaker/ state=directory mode=0644
#
#- name: Copy beaker.conf
#  template: src=beaker.conf dest=/etc/beaker/client.conf mode=0644

- name: Install aptitude
  command: apt-get install aptitude
  sudo: yes

- name: Updating all packages
  apt:  upgrade=yes update_cache=yes state=latest
  sudo: yes

- name: install by apt
  sudo: yes
  action: apt pkg={{item}} state=installed
  with_items:
    - curl
    - vim
    - libxslt1-dev
    - libxml2-dev
    - unzip
    - nginx
    - vim
    - ruby
    - byobu
    - htop
    # dev tools
    - python-dev
    - python-pip
    - python-psycopg2



#- name: Creating folder for install software
#  file: path=/home/{{ username }}/install_software owner=$username group=$username state=directory

- name: install dep-lib
  sudo: yes
  pip: name={{ item }} extra_args='-U'
  with_items:
   - fluent-logger
   - line_profiler
   - flask
   - requests
   - kazoo
   - ipython
   - virtualenv
   - virtualenvwrapper

- name: Enabling Oracle JDK 7 PPA
  sudo: yes
  apt_repository: repo=ppa:webupd8team/java



- name: Installing Oracle JDK 7
  sudo: yes
  apt: pkg=oracle-java7-installer state=latest update_cache=yes


- name: Downloading PyCharm
  get_url: url={{ pycharm }} dest=/tmp/pycharm.tar.gz


- name: Installing PyCharm
  command: tar -xzf /tmp/pycharm.tar.gz -C /home/{{ username }}/install_software/


- name: Installing Google Chrome dependencies
  sudo: yes
  apt: name=libgconf2-4,libxss1 state=latest


- name: Downloading Google Chrome
  get_url: url={{ chrome }} dest=/tmp/google-chrome-stable_current_amd64.deb

- name: Installing Google Chrome
  sudo: yes
  shell: dpkg -i /tmp/google-chrome-stable_current_amd64.deb


- name: Installing Version Control Systems
  sudo: yes
  apt: pkg=git,mercurial,gitg,meld state=installed

- name: Configuring GIT defaults
  template: src=.gitconfig.tmp dest=/home/{{ username }}/.gitconfig owner={{ username }} group={{ username }} mode=0644 backup=yes



- name: MongoDB | Install ppa key
  sudo: yes
  apt_key: id=7F0CEB10 url=http://keyserver.ubuntu.com:11371/pks/lookup?op=get&search=0x9ECBEC467F0CEB10 state=present
- name: MongoDB | Install ppa
  sudo: yes
  apt_repository: repo='deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen' state=present
- name: MongoDB | Install package
  sudo: yes
  apt: name=mongodb state=installed


- name: Installing VLC
  sudo: yes
  apt: pkg=vlc state=latest

- name: Download nodejs {{nodejs_version_tag}}
  get_url: url={{nodejs_tarball_url}} dest={{nodejs_tmp_dir}}{{nodejs_file_name}}
  when: wanted_version_installed.rc == 1

- name: Verify SHASUM of nodejs {{nodejs_version_tag}}
  shell: curl {{nodejs_shasum_url}} | grep {{nodejs_file_name}} | sha1sum -c chdir={{nodejs_tmp_dir}}
  when: wanted_version_installed.rc == 1

- name: Unpack nodejs {{nodejs_version_tag}}
  command: tar -xvzf {{nodejs_file_name}} chdir={{nodejs_tmp_dir}}
  when: wanted_version_installed.rc == 1

- name: Compile and install nodejs {{nodejs_version_tag}}
  shell: ./configure --prefix={{nodejs_path}} && make && make install chdir={{nodejs_tmp_dir}}{{nodejs_file_tag}}
  sudo: true
  when: wanted_version_installed.rc == 1

- name: NPM Install global packages
  npm: name={{item}} global=yes
  with_items: nodejs_global_packages
