---
# Note that we run gem install commands via the shell rather than using the
# Ansible gem module, in order to play nicely with RVM

- name: Ensure Jekyll's gem dependencies are installed
  sudo: yes
  shell: gem install {{ item.name }}  {{ item.flags }}
  with_items:
    - { name: 'jekyll',   flags: '--no-ri --no-rdoc' }

- name: Install kramdown
  sudo: yes
  shell: gem install kramdown

# Print a useful warning
- name: NOTICE! You will need to exit the terminal and open a fresh terminal before you can use Jekyll
  shell: echo "-"